referral_code: 345345 # Referral code (If you don't have one, pls, use mine)

eth_rpc_url: https://eth.llamarpc.com # RPC URL (Ethereum)
sepolia_rpc_url: https://ethereum-sepolia-rpc.publicnode.com # RPC URL (Sepolia)

threads: 3

min_delay_before_start: 30  # seconds
max_delay_before_start: 60  # seconds

min_amount_to_bridge: 0.00001  # ETH
max_amount_to_bridge: 0.0003  # ETH

spin_turntable_by_percentage_of_energy: 60 # 0-100
shuffle_accounts: True  # True/False